server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/gangnam
    username: gangnam
    password: gangnam
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
